import Head from "next/head";
import Image from "next/image";
import HomeSplash from "../components/homeSplash";

interface GalleryImagesResponse {
  data: GalleryImage[];
  meta: {
    pagination: {
      page: number;
      pageCount: number;
      pageSize: number;
      total: number;
    };
  };
}
interface GalleryImage {
  id: number;
  attributes: {
    Title: string;
    createdAt: string;
    description: string;
    image: {
      data: {
        id: number;
        attributes: {
          name: string;
          url: string;
          width: number;
          height: number;
        };
      };
    };
  };
}

const IMAGE_URL_BASE = "https://api.teamtedtile.com";

export default function Home({
  images,
  notFound,
}: {
  images: GalleryImage[];
  notFound: boolean;
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeSplash />
      </main>
      {/* <main className={styles.main}>
        {notFound && <h1>Images Not Found</h1>}
        {!notFound && (
          <ul>
            <li>
              {images &&
                images.map((image: GalleryImage, index: number) => (
                  <Image
                    src={`${IMAGE_URL_BASE}${image.attributes.image.data.attributes.url}`}
                    key={index}
                    alt=""
                    width={image.attributes.image.data.attributes.width}
                    height={image.attributes.image.data.attributes.height}
                  />
                ))}
            </li>
          </ul>
        )}
      </main> */}
    </>
  );
}

// export async function getStaticProps(): Promise<
//   | {
//       props: { images: GalleryImage[]; notFound: boolean };
//     }
//   | Error
// > {
//   // https://developer.mozilla.org/en-US/docs/Web/API/fetch
//   const res = await fetch(
//     "https://api.teamtedtile.com/api/gallery-images?populate=*"
//   ).catch((e) => {
//     console.error(e);
//   });
//   if (res && res.ok) {
//     const json: GalleryImagesResponse = await res.json();
//     return { props: { images: json.data, notFound: false } };
//   } else {
//     return { props: { images: [], notFound: true } };
//   }
// }
